apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase-platform.fullname" . }}-secrets
  labels:
    {{- include "supabase-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.platform.env.JWT_SECRET | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase-platform.fullname" . }}-db
  labels:
    {{- include "supabase-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: "mysql://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "supabase-platform.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}"
