apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supabase-platform.fullname" . }}
  labels:
    {{- include "supabase-platform.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "supabase-platform.fullname" . }}-db-manager
  labels:
    {{- include "supabase-platform.labels" . | nindent 4 }}
rules:
- apiGroups: ["postgresql.cnpg.io"]
  resources: ["databases"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "supabase-platform.fullname" . }}-db-manager
  labels:
    {{- include "supabase-platform.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "supabase-platform.fullname" . }}-db-manager
subjects:
- kind: ServiceAccount
  name: {{ include "supabase-platform.fullname" . }}
  namespace: {{ .Release.Namespace }}
