apiVersion: v1
kind: Service
metadata:
  name: {{ include "supabase-platform.fullname" . }}
  labels:
    {{- include "supabase-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.platform.service.type }}
  ports:
    - port: {{ .Values.platform.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "supabase-platform.selectorLabels" . | nindent 4 }}
